import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css';
import '@/scss/styles.scss';

export const inter = Inter({
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Aizen Flow',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' data-bs-theme='dark'>
      <body className={`${inter.className}`}>{children}</body>
    </html>
  );
}
